username=your_email@example.com
password=yourPasswordHere
url=https://trello.com/
boardTitle=SampleBoard
boardTitle2=SampleBoard | Trello
title=Login Page Title
title1=Dashboard Title
logintitle=Your login page subtitle
url1=https://trello.com/u/your-username/boards
